#
# A ConfigMap spec for openldap slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://github.com/osixia/docker-openldap#beginner-guide
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-openldap.fullname" . }}-phpldapadmin
  labels:
    {{- include "helm-openldap.labels" . | nindent 4 }}
data:
  config.php: |-
    <?php
    $config->custom->commands['cmd'] = array(
      'entry_internal_attributes_show' => true,
      'entry_refresh' => true,
      'oslinks' => true,
      'switch_template' => true
    );

    $config->custom->commands['script'] = array(
      'add_attr_form' => true,
      'add_oclass_form' => true,
      'add_value_form' => true,
      'collapse' => true,
      'compare' => true,
      'compare_form' => true,
      'copy' => true,
      'copy_form' => true,
      'create' => true,
      'create_confirm' => true,
      'delete' => true,
      'delete_attr' => true,
      'delete_form' => true,
      'draw_tree_node' => true,
      'expand' => true,
      'export' => true,
      'export_form' => true,
      'import' => true,
      'import_form' => true,
      'login' => true,
      'logout' => true,
      'login_form' => true,
      'mass_delete' => true,
      'mass_edit' => true,
      'mass_update' => true,
      'modify_member_form' => true,
      'monitor' => true,
      'purge_cache' => true,
      'query_engine' => true,
      'rename' => true,
      'rename_form' => true,
      'rdelete' => true,
      'refresh' => true,
      'schema' => true,
      'server_info' => true,
      'show_cache' => true,
      'template_engine' => true,
      'update_confirm' => true,
      'update' => true
    );

    $config->custom->appearance['custom_templates_only'] = true;
    $config->custom->appearance['disable_default_template'] = false;
    $config->custom->appearance['minimalMode'] = false;
    $config->custom->appearance['tree_filter'] = '(objectclass=*)';

    $config->custom->confirm['create'] = false;
    $config->custom->confirm['update'] = false;

    $config->custom->appearance['friendly_attrs'] = array(
      'facsimileTelephoneNumber' => 'Fax',
      'gid'                      => 'Group',
      'mail'                     => 'Email',
      'telephoneNumber'          => 'Telephone',
      'uid'                      => 'User Name',
      'userPassword'             => 'Password',
      'AstExtension'             => 'PBX Extension',
      'givenName'                => 'First Name',
      'sn'                       => 'Last Name',
      'cn'                       => 'Common Name'
    );

    $config->custom->appearance['hide_attrs'] = array(
      'objectClass',
      'uidnumber',
      'guidNumber'
    );

    $config->custom->appearance['attr_display_order'] = array(
      'givenName',
      'sn',
      'cn',
      'displayName',
      'uid',
      'uidNumber',
      'gidNumber',
      'homeDirectory',
      'mail',
      'userPassword'
    );

    $servers = new Datastore();
    $servers->newServer('ldap_pla');
    $servers->setValue('server','name','My LDAP Server');
    $servers->setValue('server','host','127.0.0.1');
    $servers->setValue('server','port', {{ .Values.environment.LDAP_PORT_NUMBER }} );
    $servers->setValue('login','auth_type','session');
    $servers->setValue('login','bind_id','cn={{ .Values.environment.LDAP_ADMIN_USERNAME }},dc={{ .Values.environment.LDAP_DOMAIN | replace "." ",dc=" }}');

    ?>

  custom_ou.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE template SYSTEM "template.dtd">

    <template>
    <askcontainer>1</askcontainer>
    <description>New Organisational Unit</description>
    <icon>ldap-ou.png</icon>
    <invalid>0</invalid>
    <rdn>ou</rdn>
    <title>Organisational Unit</title>
    <visible>1</visible>

    <objectClasses>
    <objectClass id="organizationalUnit"></objectClass>
    </objectClasses>

    <attributes>
    <attribute id="ou">
      <display>Organisational Unit</display>
      <hint>don't include "ou="</hint>
      <order>1</order>
      <page>1</page>
    </attribute>
    </attributes>

    </template>

  custom_user.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE template SYSTEM "template.dtd">

    <template>
      <askcontainer>1</askcontainer>
      <description>New User Account</description>
      <icon>ldap-user.png</icon>
      <invalid>0</invalid>
      <rdn>uid</rdn>
      <regexp>^ou=Users,ou=Accounts,*,</regexp>
      <title>User Account</title>
      <visible>1</visible>

      <objectClasses>
        <objectClass id="inetOrgPerson"></objectClass>
        <objectClass id="posixAccount"></objectClass>
        <objectClass id="shadowAccount"></objectClass>
        <objectClass id="PostfixBookMailAccount"></objectClass>
        <objectClass id="AsteriskSIPUser"></objectClass>
      </objectClasses>

      <attributes>

        <attribute id="givenName">
          <display>First name</display>
          <icon>ldap-uid.png</icon>
          <onchange>=autoFill(cn;%givenName% %sn%)</onchange>
          <onchange>=autoFill(uid;%givenName|0-1/l%%sn/l%)</onchange>
          <order>1</order>
          <page>1</page>
        </attribute>
        <attribute id="sn">
          <display>Last name</display>
          <onchange>=autoFill(cn;%givenName% %sn%)</onchange>
          <onchange>=autoFill(uid;%givenName|0-1/l%%sn/l%)</onchange>
          <onchange>=autoFill(homeDirectory;/home/users/%uid|0-1/l%/%uid%)</onchange>
          <order>2</order>
          <page>1</page>
        </attribute>
        <attribute id="cn">
          <display>Common Name</display>
          <order>3</order>
          <page>1</page>
          <spacer>1</spacer>
        </attribute>
        <attribute id="gidNumber">
          <display>GID Number</display>
          <order>4</order>
          <page>1</page>
          <value><![CDATA[=php.PickList(/;(&(objectClass=posixGroup));gidNumber;%cn%;;;;cn)]]></value>
        </attribute>
        <attribute id="uid">
          <display>User ID</display>
          <onchange>=autoFill(homeDirectory;/home/users/%uid%)</onchange>
          <onchange>=autoFill(mail;%uid%@{{ .Values.environment.LDAP_DOMAIN }})</onchange>
          <order>5</order>
          <page>1</page>
          <spacer>1</spacer>
        </attribute>
        <attribute id="mail">
          <display>Email</display>
          <order>6</order>
          <page>1</page>
        </attribute>
        <attribute id="AstExtension">
          <order>6</order>
          <page>1</page>
          <value>=php.GetNextNumber(/;uidNumber)</value>
        </attribute>
        <attribute id="userPassword">
          <display>Password</display>
          <icon>lock.png</icon>
          <order>7</order>
          <post>=php.PasswordEncrypt(%enc%;%userPassword%)</post>
          <page>1</page>
          <verify>1</verify>
        </attribute>


        <attribute id="uidNumber">
          <display>UID Number</display>
          <order>8</order>
          <page>2</page>
          <readonly>1</readonly>
          <value>=php.GetNextNumber(/;uidNumber)</value>
        </attribute>
        <attribute id="jpegPhoto">
          <display>Photo</display>
          <order>9</order>
          <page>2</page>
          <spacer>1</spacer>
        </attribute>
        <attribute id="o">
          <display>Organisation</display>
          <order>10</order>
          <page>2</page>
        </attribute>
        <attribute id="street">
          <cols>50</cols>
          <display>Street</display>
          <icon>mail.png</icon>
          <order>11</order>
          <page>2</page>
          <rows>4</rows>
          <type>textarea</type>
        </attribute>
        <attribute id="l">
          <display>City</display>
          <order>12</order>
          <page>2</page>
        </attribute>
        <attribute id="st">
          <display>State</display>
          <order>13</order>
          <page>2</page>
        </attribute>
        <attribute id="postalCode">
          <display>Postal code</display>
          <order>14</order>
          <page>2</page>
          <spacer>1</spacer>
        </attribute>
        <attribute id="telephoneNumber">
          <display>Work phone</display>
          <icon>phone.png</icon>
          <order>15</order>
          <page>2</page>
        </attribute>
        <attribute id="facsimileTelephoneNumber">
          <display>Fax</display>
          <order>16</order>
          <page>2</page>
        </attribute>
        <attribute id="mobile">
          <display>Mobile</display>
          <order>17</order>
          <page>2</page>
        </attribute>      
        
      </attributes>
    </template>