#
# A ConfigMap spec for openldap slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://github.com/osixia/docker-openldap#beginner-guide
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-openldap.fullname" . }}-nginx
  labels:
    {{- include "helm-openldap.labels" . | nindent 4 }}
data:
  app.conf: |
    server {
      listen 0.0.0.0:8080;

      root /app/htdocs;

      location / {
        try_files $uri $uri/index.php;
      }

      location ~ \.php$ {
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
  info.php: |
    <?php
    echo phpinfo();
    ?>