apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-openldap.fullname" . }}-phpldapadmin
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "helm-openldap.fullname" . }}-phpldapadmin
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "alpine"
          command: ["/bin/sh","/install.sh"]
          volumeMounts:
            - name: jobs
              mountPath: /install.sh
              subPath: phpldapadmin-install.sh
            - name: jobs
              mountPath: /config.php
              subPath: phpldapadmin-config.php
            - name: phpldapadmin-data
              mountPath: /app
      volumes:
        - name: jobs
          configMap:
            name: {{ include "helm-openldap.fullname" . }}-jobs
        - name: phpldapadmin-data
          persistentVolumeClaim:
            claimName: {{ include "helm-openldap.fullname" . }}-phpldapadmin
        