apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-openldap.fullname" . }}-phpldapadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi